apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerizeanddeploy
  labels:
    app: containerizeanddeploy
  namespace: namespace-workflow-1689750990940
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerizeanddeploy
  template:
    metadata:
      labels:
        app: containerizeanddeploy
    spec:
      containers:
        - name: containerizeanddeploy
          image: acrworkflow1689750990940.azurecr.io/image-workflow-1689750990940:latest
          ports:
            - containerPort: 8000