apiVersion: v1
kind: Service
metadata:
  name: containerizeanddeploy
  namespace: namespace-workflow-1689750990940
spec:
  type: LoadBalancer
  selector:
    app: containerizeanddeploy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000