apiVersion: v1
kind: Service
metadata:
  name: adfadf
  namespace: namespace-workflow-1689749238911
spec:
  type: LoadBalancer
  selector:
    app: adfadf
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000